DROP TABLE  EMPLOYEE_LOG;
DROP SEQUENCE EmployeeIDLog;

CREATE SEQUENCE EmployeeIDLog INCREMENT BY 1 START WITH 1;
CREATE TABLE  EMPLOYEE_LOG(EmployeeIDLog INT NOT NULL PRIMARY KEY, FirstName VARCHAR(255), LastName VARCHAR(255), Email VARCHAR(255), Password VARCHAR(255), Salary INT, MOD_USER VARCHAR2(10), MOD_TIMESTAMP DATE);